### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by amphiware-alex** [Quobject/SocketIoClientDotNet#100]
In our implementation, the client needs to talk to the socketio server (node.js) over https with self-signed certificate. is there a way to assign the ssl context to the socket.io client?

we could do this with iPhone/Android, but i have no clue how we could do this on dotnetclient

Thanks,
Alex

**Comment by FrankPetrilli** [comment]
Use this code:


```
IO.Options options = new IO.Options ();
options.IgnoreServerCertificateValidation = true;
socket = IO.Socket(url, options);
```

**Comment by amphiware-alex** [comment]
This just blindly trust all the self-signed certificate. 
I traced the source code and found out that webclient does have this functionality to take self-signed certificate, but the engine-io-client does not port this.
Will you guys plan to include this feature in the near future?

**Comment by mattqs** [comment]
It is only me and I am not using this library at the moment. I moved to typescript.
