### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by AmerSelimovic** [Quobject/SocketIoClientDotNet#114]
I have problems with this exception. It is appearing sometimes and crashing my app. Any way to solve it?
An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in EngineIoClientDotNet.dll

**Comment by mattqs** [comment]
https://github.com/Quobject/EngineIoClientDotNet/issues/24#issuecomment-325396793
