### ISSUE TITLE
how to emit like a node client

### ISSUE THREAD

**Issue by liyu001989** [Quobject/SocketIoClientDotNet#129]
I use a node client   ,code like this

```
socket.emit('subscribe', {
         channel: 'foobar',
})
```

but when my workmate use this client to emit subscribe，he can't let second param has a key channel. how to trans this code to .net

**Comment by liyu001989** [comment]
my workmate do it like this,  it works
```
var mess = new JObject();
mess.Add("channel", "foobar");

socket.Emit("subscribe", mess);
```

**Comment by psummo** [comment]
@liyu001989 your connection remain open?
