### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by muoi** [Quobject/SocketIoClientDotNet#139]
I tried disabling the logger but the messages still comes through. How do I disable it?

![image](https://user-images.githubusercontent.com/536678/36519783-05301724-17c0-11e8-807b-27fde8a2db17.png)

**Comment by juanluelguerre** [comment]
Hi @muoi ,
Can you provide more code (just a Little sample)? I think this a bug solved on #152

**Comment by muoi** [comment]
Yep I think that fixed it. I updated to the latest nuget package and the problem was gone. Thanks
