### ISSUE TITLE
Seemingly not working with socket.io v2.1

### ISSUE THREAD

**Issue by esbennn** [Quobject/SocketIoClientDotNet#141]
I have used this library with previous projects with success, and am currently working on a new one. 
Installing express and socket.io locally by my app.js, things worked perfectly on my js client.
I couldn't, however, get my C# client to connect. 
After some of investigating, it turned out, that copying the `node_modules` folder from an older project to this project, it suddenly worked. No differences in my code. 

Socket.io version in older project (that works):
```
[playground@darkgreen server] $ npm list |grep socket
└─┬ socket.io@1.7.2
  ├─┬ socket.io-adapter@0.5.0
  │ └── socket.io-parser@2.3.1 deduped
  ├─┬ socket.io-client@1.7.2
  │ ├── socket.io-parser@2.3.1 deduped
  └─┬ socket.io-parser@2.3.1 
```

Socket.io version in my current (non-functional project):

```
[playground@darkgreen Server] $ npm list |grep socket
└─┬ socket.io@2.1.0
  ├── socket.io-adapter@1.1.1
  ├─┬ socket.io-client@2.1.0
  │ ├── socket.io-parser@3.2.0 deduped
```
**Edit** - errors no longer show up after reinstalling libraries, but it still does not work.

**Comment by mattqs** [comment]
From the [readme:](https://github.com/Quobject/SocketIoClientDotNet#socketioclientdotnet)

This is the Socket.IO Client Library for C#, which is ported from the JavaScript client version **1.1.0.**


I recommend you do not use this code with version 2.
