### ISSUE TITLE
Package 1.0.6 built without netstandard support

### ISSUE THREAD

**Issue by ByronAP** [Quobject/SocketIoClientDotNet#145]
Version 1.0.6 was released without support for netstandard.

Targeted frameworks are:
.NETFramework 3.5
.NETFramework 4.0
.NETFramework 4.5

REF: https://www.nuget.org/packages/SocketIoClientDotNet/1.0.6

**Comment by mattqs** [comment]
https://github.com/kerryjiang/WebSocket4Net does not support netstandard 2.0 and visual studio does not support netstandard 1.3 anymore.  

That means building SocketIoClientDotNet with netstandard is currently not possible.

**Comment by KevinKibler** [comment]
Can you elaborate? As far as I can tell, WebSocket4Net already supports .NET Standard 1.3, so it should support any later version of the standard, too. Is there something specific that doesn't work?

Also, I'm able to use Visual Studio (pro 15.7.2) to target and build projects for .NET Standard 1.3, so it doesn't seem like that should be a limiting factor either. Is there something specific there that doesn't work?
