### ISSUE TITLE
no socket for namespace undefined

### ISSUE THREAD

**Issue by sinikami** [Quobject/SocketIoClientDotNet#147]
hi, there
I found latest SocketIoClientDotNet does not support namespace. like http://localhost:5000/foo

I figured out the problem at file “SocketIoClientDotNet\\Src\\SocketIoClientDotNet.net45\\Parser\\Parser.cs”  
 if (obj.Data != null)
 {
    if (nsp) str.Append(",");
    str.Append(obj.Data);       
 }

when  data is empty not null it will append  {} empty JsonObject, but at server side actuary need empty

server required : 0/foo,
but
client send: 0/foo,{}

I just simply did this and it is working very well。
   if (obj.Data != null)
                {
                    if (nsp) str.Append(",");
                   if ((obj.Data as JToken).HasValues)
                    {
                        str.Append(obj.Data);
                    }
 }

I believe you have the best way to solve this issue。

yours sincerely

**Comment by jacargentina** [comment]
Having the same problem, but the `Parser.cs` file you point is not changed since 4 years ago; may be this is related to a change on the server implementation ?
