### ISSUE TITLE
Add compatibility to .NET Core

### ISSUE THREAD

**Issue by lorenzo93** [Quobject/SocketIoClientDotNet#155]
Hi,

I've been using your library during the last month with .NET Core 2.0 without any problems despite it is officially not compatibile with Core.

It is possible to extend the official compatibility?

**Comment by khancyai** [comment]
Yeah me to, is it will be compatibility with netcoreapp?

**Comment by KevinKibler** [comment]
I think everything this project depends on were added to .NET Standard 2.0. I added explicit support to EngineIoClientDotNet here: https://github.com/Quobject/EngineIoClientDotNet/issues/61. Just waiting on a release now, then I can add support here.

**Comment by mattqs** [comment]
Support for NetStandard will be added again when WebSocket4Net works with .NETStandard 2.0. See #145
https://www.microsoft.com/net/download/visual-studio-sdks
And see https://www.nuget.org/packages/WebSocket4Net/0.15.2#
