### ISSUE TITLE
Add support for .NET Standard 2.0

### ISSUE THREAD

**Issue by KevinKibler** [Quobject/SocketIoClientDotNet#156]
Once https://github.com/Quobject/EngineIoClientDotNet/issues/61 is done, this should be trivial. There's already a project (SocketIoClientDotNet.netstandard1.3) that seems to have tried to do this. It could be renamed/copied, the reference to EngineIoClientDotNet updated, and compiled without any source code changes.

**Comment by mattqs** [comment]
https://github.com/Quobject/SocketIoClientDotNet/issues/146
