### ISSUE TITLE
compatiblity with net core 2.1

### ISSUE THREAD

**Issue by khancyai** [Quobject/SocketIoClientDotNet#159]
Hi,
I have to update my project to 2.1 currently using 2.0 because  it's depends on it for core app. 
Is it will be develop to 2.1? Because this version keep me out dated. Visual studio pm aborting update package because it's not compatible to 2.1!
Thank you.

**Comment by mattqs** [comment]
https://github.com/Quobject/SocketIoClientDotNet/issues/146
