### ISSUE TITLE
Could it support UWP?

### ISSUE THREAD

**Issue by ldbfrank** [Quobject/SocketIoClientDotNet#165]
The latest version can't instrall in VS 2017 from nuget.
It's seems Windows platform so crazy now, WinForm, WPF, UWP......

**Comment by mattqs** [comment]
Support for NetStandard will be added again when [WebSocket4Net](https://www.nuget.org/packages/WebSocket4Net/0.15.2#) works with .NETStandard 2.0. See https://github.com/Quobject/SocketIoClientDotNet/issues/145
https://www.microsoft.com/net/download/visual-studio-sdks
