### ISSUE TITLE
Not compatible with Mono.Android

### ISSUE THREAD

**Issue by dev-aritra** [Quobject/SocketIoClientDotNet#175]
This package is not comapatible with Mono.Android or Mono.Touch, hence doesn't work on Xamarin.

**Comment by jaykumarthaker** [comment]
No need to jump to a conclusion without doing proper research!
Xamarin support started from version 0.9.12 itself!

It's just the latest version stopped the .NetStandard support! #146 

[This](https://github.com/Quobject/SocketIoClientDotNet/issues/127#issuecomment-348021896) will help you out!

**Comment by dev-aritra** [comment]
@jaykumarthaker  Hi Jay,
Thanks for the clarification.

I was trying to use these on a Xamarin forms solution, which has a .net standard 2.0 project, a monoandroid8.1 project, and a xamarinios10.
So while installing I am getting a warning like "SocketIoClientDotNet 1.0.7 is not compatible with xamarinios10", same for monoandroid as well.
And on deploying I am getting error like "Could not load assembly 'SocketIoClientDotNet, Version=1.0.7.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?"

Not sure this is because the .net standard support has been revoked or it doesn't support mono frameworks? 

So can you tell by downgrading can I get it working on my project?

**Comment by dev-aritra** [comment]
@jaykumarthaker Thanks man, it works with 1.0.5.
