### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by EReeves** [Quobject/SocketIoClientDotNet#21]
Hi, I'm having an issue with a socket.io message creating a parser error.

After emitting a connection request the server sends back some json to "game/1333070/gamedata" but it results in a parser error.

I captured the traffic and the packets are arriving just fine and in tact.

          ...
          ["game/1333070/gamedata",{"handicap":0,"disable_analysis":false,
          ...

Any ideas?

        static void Main(string[] args)
        {
            var ogsSocket = IO.Socket("http://ggs.online-go.com/");
            ogsSocket.On(Socket.EVENT_CONNECT, () =>
            {
                Console.WriteLine("Connected");
            });

            var jObj = new JObject
            {
                {"game_id", 1333070},
                {"player_id", 78080},
                {"chat", false}
            };

            ogsSocket.On("game/1333070/gamedata", (data) =>
            {
                Console.WriteLine("Doesn't fire.");
            });

            ogsSocket.On(Socket.EVENT_ERROR, (data) =>
            {
                Console.WriteLine("message: server error code: parser error");
            });

            ogsSocket.Emit("game/connect", jObj);

            Console.Read();
        }

Thanks.

**Comment by mattqs** [comment]
Could you please post the code needed to reproduce the error as a test case?

I need the code for client and server:
 
The client test should look like something like this: 
 

        [Fact]
        public void MessageTest()
        {
            var log = LogManager.GetLogger(Global.CallerName());
            log.Info("Start");
            ManualResetEvent = new ManualResetEvent(false);
            var events = new Queue<object>();

            var options = CreateOptions();
            var uri = CreateUri();
            socket = IO.Socket(uri, options);
            socket.On(Socket.EVENT_CONNECT, () =>
            {
                log.Info("EVENT_CONNECT");
                socket.Emit("parser_error#21");
            });

            socket.On("parser_error#21_response",
                (data) =>
                {
                    log.Info("EVENT_MESSAGE");
                    events.Enqueue(data);
                    ManualResetEvent.Set();
                });

            //socket.Open();
            ManualResetEvent.WaitOne();
            socket.Close();
            var obj = events.Dequeue();
            Assert.Equal("more data", obj);
        }

and would go into: https://github.com/Quobject/SocketIoClientDotNet/blob/master/Src/SocketIoClientDotNet.Tests.net45/ClientTests/ServerConnectionTest.cs


and the server code should look like:

		socket.on('parser_error#21', function (d) {
		  console.log("hi" + d);
		  socket.emit('parser_error#21_response','data that causes parser error');
		});

and would go into: https://github.com/Quobject/SocketIoClientDotNet/blob/master/TestServer/server.js

**Comment by EReeves** [comment]
Forked and added the test case.
https://github.com/EReeves/SocketIoClientDotNet

**Comment by mattqs** [comment]
I ran the test case and it was passing!

You need to produce a test case that is showing the parser error you are getting.

**Comment by EReeves** [comment]
Huh, ok thanks. I'll see if I can reproduce it. Maybe its something on the server end.

**Comment by mattqs** [comment]
I have added 心の光 as username to the test data and the test is still passing.

b95770e4a456437903fb45488c6110861ee75809

**Comment by EReeves** [comment]
Yeah, that test passes for me, the content is the same but the data that is received for the message is different to that of the external socket.io server.

On the test this goes in to the parser `"3370:42[\"parser_error#21_response\",\"{\\\"handica ..."`
On the external server this goes in to it `"42[\"game/1333070/gamedata\",{\"handica ..."`

There is a UTF8 Exception thrown in the ReadContinuationByte() Method in EngineIO / UTF8.cs

I can't find any documentation, Is this normal for the socket.io protocol? As far as I am aware the external server uses a plain socket.io install. 

I have a feeling this is the reason for this issue occurred and passed too https://github.com/Quobject/SocketIoClientDotNet/issues/20

**Comment by mattqs** [comment]
The test returns a string: `\",\"{\\\"handic...`.
The external server returns a json object: `a\",{\"handica`

**Comment by EReeves** [comment]
Oh ok, So the library doesn't support json objects in this format or is it something else?

If that's the case I'll just modify it to return as a string.

**Comment by EReeves** [comment]
It's using 1.2.1 as well. It works in Javascript.

What version of EngineIO is EngineIOClientDotNet a port of? I was reading up and it seems there were some major UTF-8 continuation byte issues with versions prior to 1.3.2

https://github.com/Automattic/socket.io/issues/1744

**Comment by mattqs** [comment]
The issue Automattic/socket.io#1744 was fixed in engine.io [Invalid continuation byte in utf8.js (Error thrown) #264](https://github.com/Automattic/engine.io/issues/264) and was only happening now and then.

It was fixed by wraping it in a try-catch [see diff](https://github.com/Automattic/engine.io-parser/commit/4dc1a137500e7749fc59b384d567d576677bed0f#diff-6d186b954a58d5bb740f73d84fe39073).

The parser in EngineIoClientDotNet has a try catch [see Packet.cs line 136] (https://github.com/Quobject/EngineIoClientDotNet/blob/master/Src/EngineIoClientDotNet.mono/Parser/Packet.cs).

It is very hard to fix an error that cannot be reproduced.

Do you have a stacktrace of the error? Is it only happening occasionally? 

You could remove the nuget dependency of EngineIoClientDotNet and add the actual source code project to SocketIoClientDotNet. Then you can debug the error better.

Can you sent any messages at all?

**Comment by EReeves** [comment]
Yeah I just wanted to make sure that wasn't it, I'll debug it tomorrow, I just haven't had time.

Thanks

**Comment by EReeves** [comment]
So I sat down and debugged it, I think the utf8 decoding is redundant? websocket4net already seems to decode it in to a readable C# string. I wasn't able to produce any errors after removing the decoding entirely from engineio but my test server broke again so I only tested it on the api that I am using. I don't have time to mess around with it and it works for everything I'm using so I'll just go with this for now.

https://github.com/EReeves/EngineIoClientDotNet/commit/11641df26a803d6f0685dff0925339a60fe07960

Also thanks so much for your help, I should have made the time to sit down and debug it properly from the start rather than bother you so much, I'll make sure to donate some more sometime in the future. This project saved me heaps of time. :+1:

**Comment by mattqs** [comment]
Closed issue.
