### ISSUE TITLE
Install on mono?

### ISSUE THREAD

**Issue by nicolasgere** [Quobject/SocketIoClientDotNet#22]
hi,
I try to use it on mono, but how to install it on mono? thanks a lot

**Comment by mattqs** [comment]
This is the way I do it:

I use Visual Studio on Windows to make a project xyz. Use nuget to get the library. Then on linux I clone the git project xyz and restore the nuget package:

    mono --runtime=v4.0.30319 /path_to_nuget/nuget.exe restore /path_to_solution/xyz.sln

And then build and run.

You could also use monodevelop with nuget: e.g. http://askubuntu.com/questions/481002/how-to-install-nuget-addin-for-monodevelop
