### ISSUE TITLE
EngineIOException when node server sends latin characters to client

### ISSUE THREAD

**Issue by c1oud45** [Quobject/SocketIoClientDotNet#24]
I'm having an issue that is showing 9 out of 10 runs; program fails throwing an EVENT_ERROR ->
Error: Quobject.EngineIoClientDotNet.Client.EngineIOException: server error

Here is the smallest program to reproduce the issue:

//test.js//------------------------------------------------------------------------------------------------
var http = require('http');

var app = http.createServer(function(req, res) {
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end("<html><head></head><body>Hi!</body></html>");
});

var io = require('socket.io').listen(app);

var nsp = io.of('/W00002');
nsp.on('connection', function(socket){
    socket.on('latin', function(wsinput) {
        socket.emit('latin', {'error' : 'Nombre de usuario o contraseña incorrecta.'}); // ñ,á,é,í,ó,ú, fails
    });

    socket.on('nolatin', function(wsinput) {
        socket.emit('nolatin', {'error' : 'Nombre de usuario o contrasena incorrecta.'});
    });
});

app.listen(3000);
//------------------------------------------------------------------------------------------------------------

//Program.cs----------------------------------------------------------------------------------------------
using System;
using Quobject.SocketIoClientDotNet.Client;

namespace ConsoleApplication1 {
	class Program {
		static void Main(string[] args) {
			Manager manager;
			Socket socket;
			IO.Options options = new IO.Options();			
			options.Port = 3000;
			options.Hostname = "localhost";
			options.Secure = false;
			options.ForceNew = true;
			options.Reconnection = true;

			var uri = string.Format("{0}://{1}:{2}", options.Secure ? "https" : "http", options.Hostname, options.Port);

			manager = new Manager(new Uri(uri), options);
			socket = manager.Socket("/W00002");

			socket.On(Socket.EVENT_CONNECT, (data) => {
				Console.WriteLine("Connected!");

				socket.Emit("latin", "");
				socket.Emit("latin", "");
				socket.Emit("latin", "");
				socket.Emit("latin", "");
				socket.Emit("latin", "");
				System.Threading.Thread.Sleep(1000);

				socket.Emit("nolatin", "");
				socket.Emit("nolatin", "");
				socket.Emit("nolatin", "");
				socket.Emit("nolatin", "");
				socket.Emit("nolatin", "");
				System.Threading.Thread.Sleep(1000); //removing this line (or having less sleep time) decreaces the chances of failing
			});

			socket.On(Socket.EVENT_ERROR, (data) => {
				Console.WriteLine("Error: " + data);
			});

			socket.On("latin", (data) => {
				Console.WriteLine("latin: " + data);
			});

			socket.On("nolatin", (data) => {
				Console.WriteLine("nolatin: " + data);
			});

			Console.ReadLine();
		}
	}
}
//-----------------------------------------------------------------------------------------------------------

.Net Console OUTPUT:
Connected!
Error: Quobject.EngineIoClientDotNet.Client.EngineIOException: server error
Error: Quobject.EngineIoClientDotNet.Client.EngineIOException: server error
Error: Quobject.EngineIoClientDotNet.Client.EngineIOException: server error
Error: Quobject.EngineIoClientDotNet.Client.EngineIOException: server error
Error: Quobject.EngineIoClientDotNet.Client.EngineIOException: server error
nolatin: {
  "error": "Nombre de usuario o contrasena incorrecta."
}
nolatin: {
  "error": "Nombre de usuario o contrasena incorrecta."
}
nolatin: {
  "error": "Nombre de usuario o contrasena incorrecta."
}
nolatin: {
  "error": "Nombre de usuario o contrasena incorrecta."
}
nolatin: {
  "error": "Nombre de usuario o contrasena incorrecta."
}

Here´s everything needed to test (win) https://mega.co.nz/#!4lBl0L7D!9Sg5OsqcmEClFV2lmb8mzoKem-2Q1fpdF5Yskwf8mqo

**Comment by mattqs** [comment]
Fixed in 0.9.9.
