### ISSUE TITLE
.NET Framework 4.0

### ISSUE THREAD

**Issue by JohnKiller** [Quobject/SocketIoClientDotNet#25]
Hi, any plans for porting this amazing library on .NET 4.0?

I can't use .NET 4.5 and the 3.5 requires System.Threading.Tasks.Unofficial that give me some problems when debugging... I think this could be working without modifications by copying files from 4.5, but I need to do this also on the other library EngineIoClientDotNet.

If I do it manually, are there any other dependencies not available on 4.0?

Thanks

**Comment by mattqs** [comment]
Done in 0.9.10.
