### ISSUE TITLE
Can't add package from NuGet for Xamarin iOS project target

### ISSUE THREAD

**Issue by jmorin927** [Quobject/SocketIoClientDotNet#26]
When I try to add the SocketIoClientDotNet package to my iOS project in Xamarin, I get the following:

Adding SocketIoClientDotNet...
Downloading SocketIoClientDotNet 0.9.10...
The SocketIoClientDotNet package has a license agreement which is available at http://opensource.org/licenses/MIT
Please review this license agreement and remove the package if you do not accept the agreement.
Check the package for additional dependencies which may also have license agreements.
Using this package and any dependencies constitutes your acceptance of these license agreements.
Installing 'SocketIoClientDotNet 0.9.10'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/net35'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/net40'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/net45'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/netcore45'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/portable-win81+wpa81'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/portable-wpa81+wp81'.
Added file 'SocketIoClientDotNet.dll' to folder 'SocketIoClientDotNet.0.9.10/lib/windowsphone8'.
Added file 'SocketIoClientDotNet.0.9.10.nupkg' to folder 'SocketIoClientDotNet.0.9.10'.
Successfully installed 'SocketIoClientDotNet 0.9.10'.
Adding 'SocketIoClientDotNet 0.9.10' to MobileClient.iOS.
Could not install package 'SocketIoClientDotNet 0.9.10'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any suggestions on how to resolve this?

Thank you so much for continuing to update this project.

Regards,

**Comment by Harigharan** [comment]
Hi jmorin927,

I am also facing same issue while adding the package in xamarin studio. did you resolved those issues?

**Comment by rpmobile** [comment]
Mattqs - since you marked this an enhancement, is there some other way of integrating this library in a Xamarin project?  We appear to be blocked since we can't install via PCL.  Please let me know if I'm missing something.

**Comment by mattqs** [comment]
Compile the code yourself in Xamarin without using Nuget?

**Comment by rpmobile** [comment]
Sorry I should have been clearer in my earlier post.  I did try that, but got an incompatible framework error when trying to add that project to our solution.

Also should have mentioned - we have a unified API project that I'm trying to integrate this with.  Is that an issue?

**Comment by tecmobo** [comment]
So I haven't tested this but I did manage to build for both Xamarin.iOS and Xamarin.Android. I've attached links to zip files that contain the DLLs. You'll have to install Newtonsoft and, for the Android version, Websocket4Net from the nuget manager. I'll try to do a proper fork and run tests against it in the next couple of weeks.
https://s3.amazonaws.com/socketioclientdotnet/SocketIoClientDotNet.monodroid.zip
https://s3.amazonaws.com/socketioclientdotnet/SocketIoClientDotNet.monotouch.zip

**Comment by rpmobile** [comment]
Thanks! We will try it out immediately.  The monotouch zip seems to be corrupt (only 22 bytes).  Would you mind refreshing?

**Comment by tecmobo** [comment]
Whoops sorry about that. I just re-uploaded it. Should be good now.

**Comment by rpmobile** [comment]
Thank so much!  Just tested the iOS dll you linked, and it worked perfectly.  We will test out the Android one in a few days but this helps our development efforts quite a bit!

**Comment by rpmobile** [comment]
The monodroid zip only has one dll in it. Was that intentional?
We added Websocket4Net from nuget manager, but still getting compile errors:

Error CS0012: The type `Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter' is defined in an assembly that is not referenced. Consider adding a reference to assembly `EngineIoClientDotNet.monodroid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (CS0012) (socketio.android)

To be clear, the iOS bundle works perfectly - but Android looks like its missing some DLLs?

**Comment by tecmobo** [comment]
...and sorry again about that. I just uploaded a version that has that additional dependency in the zip file. Let me know if it works!

**Comment by rpmobile** [comment]
Thanks for the updated zip. Unfortunately, we cannot seem to get the Android part to work.    It looks like the Socket.EVENT_CONNECT event never fires.  

Running against the same test server, the iOS version works, but the Android one just never responds to any socket.io events.  The line:  IO.Socket("http://localhost:3000") doesn't seem cause any errors.

**Comment by tecmobo** [comment]
That's weird. I would have thought if either of them didn't work it would have been the iOS one. At any rate I haven't gotten to working with that portion of my code yet but if I figure it out I will post more info.

**Comment by tecmobo** [comment]
Sorry I haven't had a chance to attack this yet. Out of curiosity the event doesn't fire on the client but what about on the server? Does it say that a client has, and is still connected?

**Comment by jlewin** [comment]
@tecmobo Any chance you're going to share your work so that others can troubleshoot and expand on what you've done? I'd really like to use this library on Android and would love to pickup where you're currently at. thx

**Comment by rpmobile** [comment]
@tecmobo The server never sees the connection, or the subsequent disconnect.  After this command, nothing happens on server or client:

    IO.Socket("http://localhost:3000")

**Comment by tecmobo** [comment]
@jlewin item number for on my task list is "make a proper fork of socketioclient repo so that we can actually get that shiz working" :)

**Comment by jlewin** [comment]
Great. I'll keep an eye out and wait for your fork. Thanks

**Comment by RashadSaleh** [comment]
I actually tested the Android .dll's and I was able to connect to the server. Thanks @tecmobo and @mattqs for your work.

**Comment by DrLudwig** [comment]
Thanks @RashadSaleh. 

Closed issue.

**Comment by mattqs** [comment]
Thanks @RashadSaleh.

Closed issue.

**Comment by rpmobile** [comment]
@RashadSaleh would you mind sharing any test project you have for the Android client? We still cannot get the MonoDroid version to connect to the server.  We are mirroring the MonoTouch version, but perhaps we are doing something incorrectly.  

Thanks to @tecmobo and @mattqs as well.

**Comment by RashadSaleh** [comment]
I made a Xamarin.Forms shared project in Visual Studio 2015 Pro RC. Then I:
* removed the Windows Phone project.
* installed Newtonsoft.Json into the .Droid and .iOS projects. (.Droid using NuGet, .iOS by manually referencing the .dll because of a bug in NuGet 3)
* referenced websocket4net.0.11
* referenced the .dll's @tecmobo linked to.
* added this code just before `MainPage = new ContentPage { ... }` in App.cs:
```C#
    var socket = IO.Socket("http://mydomain.com");
    socket.On(Socket.EVENT_CONNECT, () =>
    {
        Console.WriteLine("CONNECTED");
    });
```

Then I started debugging the .Droid project using the new Visual Studio 2015 Android emulator, and I did get "CONNECTED" outputted in the debugger.

I haven't tested it any further. When I do, I will post my results here. If you need any more information, please let me know.

**Comment by tecmobo** [comment]
I just committed the fork I was working off of [here](https://github.com/tecmobo/SocketIoClientDotNet). Its a bit hack-ish as there are dependencies that should be obtained through nuget (EngineIoClientDotNet, etc) but obviously I don't want to put nuget builds up for those. I'll put up the fork of the EngineIoClientDotNet project and then they can integrate that into the next release.

**Comment by RashadSaleh** [comment]
I just tested again and this time I sent a simple string from the client to the server and it worked: the server broadcasted the string to everyone else and I could read it in the browser client (see image below). I haven't been able to test receiving from the server because VS2015RC runs slowly on my machine and has a bug that makes the debugger go totally unresponsive sometimes, and on top of that the new emulator makes the internet on my machine keep disconnecting momentarily but frequently. But I don't see why if it can send data it wouldn't be able to receive it.

![image](https://cloud.githubusercontent.com/assets/12851655/8145643/7ed7750a-1218-11e5-8ec3-a9cd240c32c8.png)

**Comment by RashadSaleh** [comment]
OK I finally managed to test receiving from the server and it worked:
![receivedmsgfromserver](https://cloud.githubusercontent.com/assets/12851655/8146569/af100b6a-124a-11e5-873e-77795d289894.png)

**Comment by rpmobile** [comment]
Thank you all for your help. We have it running on both platforms now.

**Comment by jlewin** [comment]
Thanks so much for everyone's work on this. We've had good luck running the compiled assemblies from this thread and are looking forward to Android support in the nuget packages. Is there anything holding up the process that could benefit from external assistance?

**Comment by mattqs** [comment]
I use java on Android and will go with https://github.com/nkzawa/socket.io-client.java. I do not intend to support Android for .net.

**Comment by mattqs** [comment]
the latest release 0.9.12 supports Xamarin-iOS, Xamarin-MonoTouch, Xamarin-Android. There is also a Xamarin compenent for it http://components.xamarin.com/view/SocketIoClientDotNet.

**Comment by rpmobile** [comment]
Excellent! Thank you. We'll integrate immediately.

**Comment by RashadSaleh** [comment]
Thank you mattqs.
