### ISSUE TITLE
No .Connect() needed?

### ISSUE THREAD

**Issue by jarekwg** [Quobject/SocketIoClientDotNet#28]
Hi!

Firstly, great work on this! :+1: 

Installing this package to replace SocketIO4Net was largely a breeze, however there were some small hiccups. I've put them each in separate issues. This first one is probably a non-issue, but thought I'd mention it anyway:

.Connect() does... ?
   It seems that IO.Socket() already does the connection for us. Is there a reason for this? It seems more intuitive (at least to me) to create the socket with IO.Socket(), then declare all the .On()s, THEN call .Connect() at the end.

cheers,
jarekwg

**Comment by mattqs** [comment]
This connect behaviour is the same as as it is in the javascript [socket.io-client](https://github.com/automattic/socket.io-client).

This .net library is a one to on translation of the javascript client into C#, and I did not want to make it different to the js client.

**Comment by c1oud45** [comment]
I think that you can get your desired behavior using an option in the manager, I think is called "autoconnect" set it to false and you can connect after the On's

**Comment by jarekwg** [comment]
Ah, I didn't see those options. Without them, the Connect method seemed pointless. Thanks!
