### ISSUE TITLE
getting gibberish when trying to emit message that contains hebrew  from .net client to node.js server

### ISSUE THREAD

**Issue by maty21** [Quobject/SocketIoClientDotNet#31]
example of  code that not working for me 
<code> 
socket.On(Socket.EVENT_CONNECT, () =>
            {         
            });
  socket.Emit("test","בדיקה");
</code>
i have to mention  that from server to client it's working fine (the message encoded correctly)
something weird  that i saw is that when I'm emitting a message from the connect event scope it works correctly (i'm getting Hebrew on the server side) as you can see in the example below 
<code> 
socket.On(Socket.EVENT_CONNECT, () =>
            {
                socket.Emit("test","בדיקה");
            });
</code>

does anyone have an idea how can i solve this issue(workaround is good as well ) 

thanks

**Comment by mattqs** [comment]
I have added a test in [ServerConnectionTest.cs](https://github.com/Quobject/SocketIoClientDotNet/blob/master/Src/SocketIoClientDotNet.Tests.net45/ClientTests/ServerConnectionTest.cs):

        [Fact]
        public void MessageTestHebrew()
        {
            var log = LogManager.GetLogger(Global.CallerName());
            log.Info("Start");
            ManualResetEvent = new ManualResetEvent(false);
            var events = new Queue<object>();

            var options = CreateOptions();


            options.Transports = ImmutableList.Create<string>(Polling.NAME);

            var uri = CreateUri();
            socket = IO.Socket(uri, options);
            socket.On(Socket.EVENT_CONNECT, () =>
            {
                log.Info("EVENT_CONNECT");
                socket.Emit("test", "csdataてすとבדיקה");
            });

            socket.On("hi",
                (data) =>
                {
                    log.Info("EVENT_MESSAGE");
                    events.Enqueue(data);
                    //socket.Emit("test", "2csdataてすとבדיקה");
                    ManualResetEvent.Set();
                });

            //socket.Open();
            ManualResetEvent.WaitOne();
            socket.Close();
            var obj = events.Dequeue();
            Assert.Equal("more data", obj);
        }
		
and a corresponding server entry in [server.js](https://github.com/Quobject/SocketIoClientDotNet/blob/master/TestServer/server.js)	
      
	  // simple test
      socket.on('test', function(d) {    
	    var s1 = "test" + d;
	    console.log(s1);
	    fs.appendFileSync('test.txt', s1);
	    socket.emit('hi', 'more data');
      });

The console output (powershell):
    testcsdata????????

The test.txt file content:
    testcsdataてすとבדיקה

There seems to be a problem with nodes console log, but the characters do arrive at the server.

**Comment by maty21** [comment]
according to what i saw the decoding not working correctly three tests that i done in order to make sure that my assumption is correct 

1. sending that string to webclient in order to view the data on UI -    i saw gibberish.

2 .created other client instead of the .net that send the data  (web client ) - works correctly i was able to see the decoded string on the console.
 
3. serialize the data to byte array on the .net client ,than deserialize and print it to the console  on  node.js server -  works correctly i was able to see the decoded string on the console
