### ISSUE TITLE
.NET 4.0?

### ISSUE THREAD

**Issue by GAumala** [Quobject/SocketIoClientDotNet#35]
Readme.me only lists .Net Framework 3.5 and .Net Framework 4.5. is 4.0 supported in the latest version? I'm having problems connecting the Socket targeting 4.0. Socket.EVENT_CONNECT_ERROR is raised all the time.

**Comment by mattqs** [comment]
.Net Framework 4.0 is supported since  0.9.10.

**Comment by GAumala** [comment]
Could you please help me I out telling me what I'm doing wrong? I'm trying to run this code in an Outlook Add-In targeting .Net Framework 4.0 and using version 0.9.10.

var options = new IO.Options();
            options.Port = 8081;
            options.Hostname = "myWebSite.com";
            options.AutoConnect = false;
            var uri = string.Format("{0}://{1}:{2}", "http", options.Hostname, options.Port);
            var socket = IO.Socket(uri, options);

            socket.On(Socket.EVENT_CONNECT, () =>
            {
                Logs.Log.LogMessage("connected");
                socket.Emit("parser_error#21");
            });

            socket.On("parser_error#21_response",
                (data) =>
                {
                    Logs.Log.LogMessage("event");
                });

            socket.On(Socket.EVENT_CONNECT_ERROR, () =>
                {
                    Logs.Log.LogMessage("Connect Error");
                });

            socket.Connect();

As for the server, I copied the code from https://github.com/Quobject/SocketIoClientDotNet/blob/master/TestServer/server.js

All I get is "Connect Error" in my log.

**Comment by mattqs** [comment]
Please try to run a simple example first e.g.:


	using Quobject.SocketIoClientDotNet.Client;
	var socket = IO.Socket("http://localhost");
	socket.On(Socket.EVENT_CONNECT, () =>
	{
		socket.Emit("hi");
		socket.On("hi", (data) =>
		{
			Console.WriteLine(data);
			socket.Disconnect();
		});
	});
	Console.ReadLine();


And then gradually change it to your situation.

**Comment by GAumala** [comment]
Thank you for the advice. I ran your sample in a new Console Project and it worked flawlessly.

However, running that code in my Outlook Add-In Project is useless. Both projects target .NET 4.0 Client Profile, and used the same server. Is there something special about Microsoft Add-Ins that I'm missing?

**Comment by DrLudwig** [comment]
I suggest you ask a question at http://stackoverflow.com/
