### ISSUE TITLE
Signing SocketIoClientDotNet with a strong name

### ISSUE THREAD

**Issue by IoTier** [Quobject/SocketIoClientDotNet#36]
I am working on a signed project and I want to reference SocketIoClientDotNet, is it possible to sign it to be able to reference it from a signed project.

**Comment by michalkrupa** [comment]
:+1:

**Comment by giacgbj** [comment]
:+1:

**Comment by jeremy-ign** [comment]
Hi, 

I had the same issue with an existing strong-named assembly and had to make a script to dynamically sign SocketIoClientDotNet (and its depedencies), if you could sign the project it would fix this issue and 
help a lot of us...,

thanks,

**Comment by jeremy-ign** [comment]
Thanks for your answer! Any comment on your decision to not fix this would greatly be appreciated and help have a better understanding.
