### ISSUE TITLE
Does not seem to work with netty-socketio

### ISSUE THREAD

**Issue by viz123** [Quobject/SocketIoClientDotNet#39]
I failed to make it work with netty-socketio. The server (netty-socketio) gives NumberFormatException when I try to Emit a json object to the server. This is a very simple use case and obviously, the server works fine when I emit from javascript. 

The exception on the server side looks like this:
....java.lang.NumberFormatException: Invalid int: "���42["chatevent",{"userName"" at java.lang.Integer.invalidInt(Integer.java:138).....

It seems the library is sending some characters that the server does not like.

**Comment by giacgbj** [comment]
:+1:

**Comment by mattqs** [comment]
There are no plans to support netty-socketio.
