### ISSUE TITLE
Support for HTTP proxy?

### ISSUE THREAD

**Issue by viz123** [Quobject/SocketIoClientDotNet#41]
Can I use this library with HTTP proxy? I did not find any example. Any help would be greatly appreciated.

**Comment by mattqs** [comment]
I don't use a proxy.
Please post this question on http://stackoverflow.com/help/how-to-ask.

**Comment by viz123** [comment]
Thanks for your quick response. I guess my question is more related to the library's ability. Many corporates allow employees to connect to the internet only through HTTP proxy. If this library does not support HTTP proxy, it cannot be used in such environments. 

I see that there is a JavaScript client that supports proxy: https://github.com/ymx/socket.io-proxy. I was wondering if HTTP proxy support already exists in your library, or is planned.

**Comment by mattqs** [comment]
I've started a new project: https://github.com/Quobject/SocketIoClientDotNet-Proxy. This will port https://github.com/ymx/socket.io-proxy to DotNet.

**Comment by viz123** [comment]
Thanks for starting the new project. 
I believe that proxy authentication is currently not supported by https://github.com/ymx/socket.io-proxy. That is another feature that would be very important as some companies ask their employees to authenticate to the proxy.

**Comment by mattqs** [comment]
I'm not very familiar with proxy implementations. Any help in implementing the new project at  https://github.com/Quobject/SocketIoClientDotNet-Proxy would be much appreciated.

**Comment by viz123** [comment]
Thanks for the invitation. My current project is keeping me very busy, but once I get time I will try to look into it, or provide some help.

**Comment by mattqs** [comment]
I still don't understand the need for this functionality.

Why would you not just set your proxy settings using the operating system e.g. in windows 8:
Internet Properties -> Connections -> LAN settings -> Proxy server

**Comment by chunkychode** [comment]
@viz123 Did you ever make any headway with proxy auth ?
Any feedback or pointers would be greatly appreciated.
