### ISSUE TITLE
Why can't connect to socket.io v1.3.5

### ISSUE THREAD

**Issue by PuthNeng** [Quobject/SocketIoClientDotNet#44]
Can you help me? I see the link : https://github.com/Quobject/SocketIoClientDotNet
connect with socket.io is ok but when I do it is still not work? What the problem? I develop on wpf C# and I use library : SocketIoClientDotNet and I follow code example.

**Comment by mattqs** [comment]
I can connect to socket.io .v1.3.5.
Please post this question on http://stackoverflow.com/help/how-to-ask.

**Comment by PuthNeng** [comment]
@mattqs Thank you for reply ):
