### ISSUE TITLE
How to remove Listener on SocketIoClientDotNet?

### ISSUE THREAD

**Issue by pheaktraty** [Quobject/SocketIoClientDotNet#46]
I have problem with show more result when I emit one time. So, I want you to help me to remove Listener. In Javacript remove list this: socket.removeListener('testComplete'); but in SocketIoClientDotNet, I don't know to remove . Do you have solution for me?.thank..!

**Comment by mattqs** [comment]
This is the Socket.IO Client Library for C#, which is ported from the [JavaScript client](https://github.com/Automattic/socket.io-client). The JavaScript client uses [component-emitter] (https://github.com/component/emitter) as event emitter component. Removing listeners are done by socket.off not by "socket.removeListener('testComplete')".

SocketIoClientDotNet uses [Quobject.EngineIoClientDotNet.ComponentEmitter] (https://github.com/Quobject/EngineIoClientDotNet/blob/master/Src/EngineIoClientDotNet.mono/ComponentEmitter/Emitter.cs) therefore removing listeners are done by socket.Off('event').

**Comment by pheaktraty** [comment]
Thank you so mush.
