### ISSUE TITLE
Issue running on mono

### ISSUE THREAD

**Issue by SjoerdNijboer** [Quobject/SocketIoClientDotNet#48]
When attempting to use this library in mono 3.12.0 or 3.3.0 an exception happens.
This does not happen when using .net

My friend and I tried to narrow it down, but can't figure it out.

example script

http://pastebin.com/0uaYvypP/

Incl: stacktrace below.

Unhandled Exception:
System.Net.Sockets.SocketException: An address incompatible with the requested protocol was used.
 
  at System.Net.Sockets.Socket..ctor (AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType) [0x
00058] in C:\cygwin\sources\mono\mcs\class\System\System.Net.Sockets\Socket_2_1.cs:953
  at SuperSocket.ClientEngine.ConnectAsyncExtension.CreateAttempSocket (SuperSocket.ClientEngine.DnsConnectState connect
State) [0x00000] in <filename unknown>:0
  at SuperSocket.ClientEngine.ConnectAsyncExtension.OnGetHostAddresses (IAsyncResult result) [0x00000] in <filename unkn
own>:0
Press any key to continue . . .

**Comment by SjoerdNijboer** [comment]
We cannot send you accestoken or client id for security reasons. But, we can show that we're doing things right, or wrong. The thing is, we're getting data send back in .net so it shouldn't be wrong

**Comment by mattqs** [comment]
I'm using the SocketIoClientDotNet library in mono under linux without any problems.

**Comment by SjoerdNijboer** [comment]
My friend, I'm not trying to be hars or something. I'm just trying to figure this out. There's clearly a stacktrace which is (correct me if I'm wrong) happening in the library.
