### ISSUE TITLE
Multiple parameter binding?

### ISSUE THREAD

**Issue by seanfar** [Quobject/SocketIoClientDotNet#51]
Greetings, 
First off, the package works great, thank you for the time you've spent on it.
I'm building a project in which the node server emits a 3 argument message. This is tested and working properly. In my .NET project, I want to be able to handle those 3 arguments, but I seem to be missing if/how this is possible with this client? Only the first argument is bound properly, while the other two are missing completely from the payload. My C# code is as follows:

```
            socket.On("remote:request", (data) =>
                {
                   //Do something with the args
                });
```

I have looked through your unit tests and didn't notice this covered anywhere. I apologize if I overlooked it. 

Any and all help is appreciated. I would be happy to provide a more detailed code snippet if necessary. Thanks!

**Comment by mattqs** [comment]
You can always write your own IListener implementation. See my comment from commented on 20 Nov 2014 in https://github.com/Quobject/SocketIoClientDotNet/issues/12

**Comment by seanfar** [comment]
Ah, thanks! Totally /facepalmed, I even looked at that thread and didn't notice the follow-up comments. Thank you again!

**Comment by mattqs** [comment]
Here is an example for an IListener implementation taking three params:

    public class ListenerImpl : IListener
    {
        private static int id_counter = 0;
        private int Id;
        private readonly Action<object,object,object> fn;

        public ListenerImpl(Action<object, object, object> fn)
        {

            this.fn = fn;
            this.Id = id_counter++;
        }

  

        public void Call(params object[] args)
        {
            if (fn != null)
            {
                var arg0 = args.Length > 0 ? args[0] : null;
                var arg1 = args.Length > 1 ? args[1] : null;
                var arg2 = args.Length > 2 ? args[2] : null;
                fn(arg0,arg1,arg2);
            }          
        }

        

        public int CompareTo(IListener other)
        {
            return this.GetId().CompareTo(other.GetId());
        }

        public int GetId()
        {
            return Id;
        }
    }
