### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by TadeoArmenta** [Quobject/SocketIoClientDotNet#52]
i got this implementation:

private Client.IO.Options CreateOptions()
{
    Client.IO.Options op = new Client.IO.Options();
    op.AutoConnect = true;
    op.Reconnection = true;
    op.ReconnectionDelay = 500;
    op.Timeout = 1000;
    op.Secure = true;
    op.ForceNew = true;
    return op;
}
private void connect()
{
    try
    {

```
    Uri uri = new Uri("https://myurl.com");
    var options = CreateOptions();
    this.socket = IO.Socket(uri,options); 

    this.socket.On(Socket.EVENT_CONNECT, () =>
    {
        this.socket.Emit("register", sharpclientidentifier);

    });
    this.socket.On(Socket.EVENT_RECONNECT, () =>
    {
        this.socket.Emit("register", sharpclientidentifier);

    });

    this.socket.On(Socket.EVENT_ERROR, (data) =>
    {
        Debug.WriteLine("Error de coneccion: " + data );
    });

    this.socket.On(Socket.EVENT_CONNECT_ERROR,(data) =>
    {
        Debug.WriteLine("Error de coneccion: " + data );
    });

    this.socket.On(Socket.EVENT_DISCONNECT, (data) =>
    {
        Debug.WriteLine("Error de coneccion: " + data);
    });

    this.socket.On(Socket.EVENT_RECONNECT_ERROR, (data) =>
    {
        Debug.WriteLine("Error de reconeccion: " + data);

    });
    this.socket.On(Socket.EVENT_CONNECT_TIMEOUT, (data) =>
    {
        Debug.WriteLine("Error de reconeccion: " + data);

    });

    this.socket.On(sharpclientidentifier, (data) =>
    {
        this.Trap(data+"");
    });
    this.socket.On("requestUpdate", (data) =>
    {
        this.socket.Emit("sharp_status_update", EstausData());

    }); 



}
catch (Exception e)
{
    log("Error al tratar de conectar al servicio web : " + e.Message);
    Debug.WriteLine("IO exception  " + e.Message);
    this.socket.Close();
    this.socket.Open();
}
```

}

Server is requesting me every 10 secs for a estatus update. with only this activity, after about 3hours, got 

A first chance exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
A first chance exception of type 'System.InvalidOperationException' occurred in System.dll
A first chance exception of type 'System.InvalidOperationException' occurred in System.dll

and a unhandled system.invalidoperationexception collection was modified enumeration operation may not execute

any help will be apreciated.

**Comment by mattqs** [comment]
Please add the line:

    Debug.WriteLine(e.StackTrace);

to your catch block and post the stacktrace of this exception.
