### ISSUE TITLE
Cannot download nuget for PCL Targetting 4.5, Win8 and WP8.1

### ISSUE THREAD

**Issue by joefroh** [Quobject/SocketIoClientDotNet#55]
I am trying to use your really handly nuget, but even with the support claimed on the front page of this repo, it doesnt seem to have a nuget published for anything but normal .net. Can't seem to get this into my portable lib.

Thoughts?

**Comment by mattqs** [comment]
I have tested it for these versions:
.Net Framework 3.5, .Net Framework 4.0, .Net Framework 4.5, Windows 8, Windows 8.1, Windows Phone 8, Windows Phone 8.1, Mono, Unity

**Comment by joefroh** [comment]
I understand that, but have you tested them using a PCL that targets multiple platforms using your nuget? There is not binary published.

**Comment by joefroh** [comment]
https://github.com/Quobject/SocketIoClientDotNet/blob/master/grunt/Gruntfile.js

You seem to be building for all plats, but only copying the release for mono and .net4.5 if i am reading your script properly.

**Comment by mattqs** [comment]
The nuget upload and the [zip file](https://github.com/Quobject/SocketIoClientDotNet/releases/download/0.9.11/SocketIoClientDotNet.0.9.11.zip)  contains dll's for all of the following:

   { "Name": "SocketIoClientDotNet.net35", "NuGetDir": "net35" },
      { "Name": "SocketIoClientDotNet.net40", "NuGetDir": "net40" },
      { "Name": "SocketIoClientDotNet.net45", "NuGetDir": "net45" },
      { "Name": "SocketIoClientDotNet.windowsphone8", "NuGetDir": "windowsphone8" },
      { "Name": "SocketIoClientDotNet.netcore45", "NuGetDir": "netcore45" },
      { "Name": "SocketIoClientDotNet.portable-wpa81+wp81", "NuGetDir": "portable-wpa81+wp81" },
      { "Name": "SocketIoClientDotNet.portable-win81+wpa81", "NuGetDir": "portable-win81+wpa81" }

**Comment by joefroh** [comment]
I dug a little further into my issue. You are correct that these are published (of course you were), but apparently if I have a PCL targetting a combination of the above it doesn't like to work.

I went a looked at the nuget package for another dependency I am using and it formats itself similar but also has:

portable-net45+wp80+win8+wpa81+dnxcore50
portable-net40+sl5+wp80+win8+wpa81

I assume there is no way I could get a build drop for that right? I need to be able to target 4.5, phone and win8 and would prefer to not have to build multiple libs

**Comment by mattqs** [comment]
Sorry, I don't have the time to do any other builds. Please use the code and build yourself.
