### ISSUE TITLE
how could i send binary data?

### ISSUE THREAD

**Issue by laoshancun** [Quobject/SocketIoClientDotNet#57]
when i send a JObject than contain  binary data , server can not get rigth things ????
![qq 20150718173811](https://cloud.githubusercontent.com/assets/4952748/8761150/f0b0d862-2d73-11e5-9634-172f84a36444.jpg)
![qq 20150718173827](https://cloud.githubusercontent.com/assets/4952748/8761151/f0c1ef4e-2d73-11e5-9f5e-1be65aabca0a.jpg)

**Comment by mattqs** [comment]
See https://github.com/Quobject/SocketIoClientDotNet/issues/31
