### ISSUE TITLE
Problem on WindowsPhone 8

### ISSUE THREAD

**Issue by quyendang** [Quobject/SocketIoClientDotNet#58]
Hi Friend,
I am Quyen, I am a WindowsPhone developer !
I am creating a chat app use node.js server on WindowsPhone 8.
But, I have a problem with SocketIoClientDotNet libary.
I have a server with hostname: 192.168.1.2, port: 3000.
and User want to connect to server need an token on socket connect! 
(token=qwertygsa).
I see on Android and IOS, I can connect with function: 
mSocket = IO.socket("http://192.168.1.2:3000/?token=qwertygsa");
mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onConnectTimeout);
mSocket.on(Socket.EVENT_CONNECT, onConnect);
mSocket.connect();

But on WindowsPhone 8, When I try to use this function, it cant connect.
It work well on android & IOS
.
Please help me ! 
Thank you !

**Comment by mattqs** [comment]
I can not reproduce this error. Please post question in stackoverflow.com.
