### ISSUE TITLE
Error while installing package to Xamarin Portable app

### ISSUE THREAD

**Issue by kindras** [Quobject/SocketIoClientDotNet#61]
Good afternoon ! 
I'm currently trying to install your solution to my application through the *NuGet Package Manager Console*. Unfortunately after several tries (updating NuGet, modifying my PCL targeting), it won't let me install SocketIoClientDotNet.
```
Start package installation to project AlarmConnection
Reference to package added: SocketIoClientDotNet 0.9.12
Installation failed. Rolling back...
Error: Could not install package 'SocketIoClientDotNet 0.9.12'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Installation finished.
```
Thanks in advance,
Best regards.

**Comment by mattqs** [comment]
SocketIoClientDotNet does not support `portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10`.

**Comment by mattqs** [comment]
re opened.

**Comment by mattqs** [comment]
I have tried to build a Xamarin Portable library but I got error:
```
Error		Could not install package 'WebSocket4Net 0.13.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

SocketIoClientDotNet relies on WebSocket4Net and because WebSocket4Net does not support `portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10` that means SocketIoClientDotNet cannot either.

@kindras you could ask WebSocket4Net to support your portable library and get back to me when they do and reopen another issue.

**Comment by mattqs** [comment]
I can't build a Xamarin Portable library because it needs WebSocket4Net:

```
Could not install package 'WebSocket4Net 0.13.1'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

```
