### ISSUE TITLE
Could not install package ('.NETPortable,Version=v4.5,Profile=Profile78')

### ISSUE THREAD

**Issue by luzianscherrer** [Quobject/SocketIoClientDotNet#64]
I've just tried installing that package but it fails with the following error:

Could not install package 'SocketIoClientDotNet 0.9.12'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Am I missing something?

**Comment by mattqs** [comment]
SocketIoClientDotNet does not work with ''.NETPortable,Version=v4.5,Profile=Profile78'.

There is a dependecy on WebSocket4Net which does not work with ''.NETPortable,Version=v4.5,Profile=Profile78'.
