### ISSUE TITLE
Cannot define query parameters in connection string

### ISSUE THREAD

**Issue by ivarsv** [Quobject/SocketIoClientDotNet#65]
The client returns invalid namespace error if query parameters are defined in connection string. 
For example: 

```csharp
IO.Socket("http://localhost/?hello=world")
``` 
The code should check if there are query parameters present. 

This can be fixed by changing io.Socket constructor in IO class: 

```csharp
if (uri.PathAndQuery.indexOf ("?") != -1) {
	String[] uriAndQueryString = uri.PathAndQuery.split ("?");

	uri = uriAndQueryString [0];
	opts.QueryString = uriAndQueryString [1];
}
```

**Comment by mattqs** [comment]
Query strings should be set by `IO.Options`:
```
var options = new IO.Options();
options.QueryString = "hello=world";
```
