### ISSUE TITLE
Memory and thread leak

### ISSUE THREAD

**Issue by men232** [Quobject/SocketIoClientDotNet#67]
Hi, i'm using SocketIoClientDotNet for .Net 4.0 and .Net 3.5 and i have some problems. This example code make memory and thread leak. After, you can see, how app opens a new thread and consumes more memory...

``` csharp
// Client
var opts = new IO.Options();
opts.Cookies.Add("test", "1");
opts.Reconnection = true;

var m_manager = new Manager(new Uri("http://mysite.com"), opts);
var socket = m_manager.Socket("/test");

socket.On(Socket.EVENT_CONNECT, () =>
{
    socket.Emit("hi");

});

socket.On("hi", (data) =>
{
    Console.WriteLine(data);
});

socket.On("statistic", (data) =>
{
    socket.Emit("statistic");
    Console.WriteLine(data);
});

Console.ReadLine();
```

``` js
// Scoket.IO Server
setInterval(function() {
    socket.emit('statistic', 'full');
}, 100);
```

**Comment by men232** [comment]
This only in .NET 3.5

**Comment by TadeoArmenta** [comment]
please, post more of your node code

**Comment by men232** [comment]
Like this:
```js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

io.on('connection', function(socket) {
	setInterval(function() {
		socket.emit('statistic');
	}, 1000);

	socket.on('statistic', function(data) {
		console.log(data);
	});	
});

var server = http.listen(1337, function() {
	var host = server.address().address;
	var port = server.address().port;

	console.log('Listening at http://' + host + ':' + port);
});
```

**Comment by TadeoArmenta** [comment]
you have to put setInterval function outside of the event ON_CONNECT, if you keep it as you have it right now, it will creates a timer for every connection, so, in other words, if you have 10 clients connected, your clients are receiving  10 emits every single second

try something like this:

``` var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);



var Default = io.of('/socket.io/');

setInterval(function() {
    Default.emit('statistic', 'full');
}, 1000);

Default.on('connection', function(socket) {

    socket.on('statistic', function(data) {
        console.log(data);
    }); 
});

var server = http.listen(1337, function() {
    var host = server.address().address;
    var port = server.address().port;

    console.log('Listening at http://' + host + ':' + port);
}); ```

**Comment by men232** [comment]
The problem is not in node. This simple node code need for detection of bugs. Soo, after C# client connect to node server, i receive messages every second. And each received message in C# client, opened new thread. After some time, i see in task manager how my app c# client uses hundreds of thread.

**Comment by TadeoArmenta** [comment]
**And each received message in C# client, opened new thread**

exactly, this is  why you have to put the setInterval function outside the connection event......

**Comment by men232** [comment]
Well, I'll try your code. But I tried the same code on .NET > 3.5 and everything was fine.

**Comment by men232** [comment]
Now my code is exactly the same as your, the problem is not exactly in this. New thread opened every received **statistic** message.

**Comment by raintean** [comment]
+1 this issue same for me

**Comment by mattqs** [comment]
Please check again with new release 1.0.0.1-beta1

**Comment by men232** [comment]
Its work fine, thx 👍
