### ISSUE TITLE
Connect to TLS server

### ISSUE THREAD

**Issue by thuron** [Quobject/SocketIoClientDotNet#68]
I've got a TLS server running on my node server and I hooked it up to Socket.io. Now I'm looking to connect my .NET client application to this server. I already successfully connected my client to a TCP node server, but connecting to a TLS server keeps giving me errors, which I'm sure are for a good reason, but before I break my head over this error I thought I'd check if this is even possible by design and if it isn't if there are ways to make it work. Any help is greatly appreciated.

Kind regards

**Comment by TadeoArmenta** [comment]
maybe i can help if you post some of your code.

**Comment by thuron** [comment]
I did some more testing with just a Socket.io server (without the TLS server) but it seems that it's impossible to add certificates to it that way so I've added the basic structure of my code below.

**Server**
```javascript
var tls = require('tls');

var options = {
	key: fs.readFileSync(appConfig.sslKey),
    cert: fs.readFileSync(appConfig.sslCert),
    ca: fs.readFileSync(appConfig.sslCertAuth)
}

var server = tls.createServer(options);

var io = require('socket.io').listen(self.server);
self.server.listen(self.port, function() {
    log.info('Server Listening')
});

io.on('connection', function(socket) {
	log.info('Connection was made')

	socket.on('request-login', function() {
		log.info('Login was requested');
		socket.write('You are now logged in.');
	})
})
```

**Client**
```c#
IO.Options opt = new IO.Options();
opt.Secure = true;
socket = IO.Socket(server, opt);
socket.On(Socket.EVENT_CONNECT, () =>
{
    Debug.WriteLine("Connected to the server.");
    socket.Emit("request-login");
});
socket.On(Socket.EVENT_CONNECT_ERROR, (err) =>
{
    Debug.WriteLine(err.ToString());
});
socket.On(Socket.EVENT_MESSAGE, (msg) =>
{
    Debug.WriteLine(msg);
});
```

I'm having no issues whatsoever when I use a plain Socket.IO server without attaching it to a TLS server and it does get all the events properly in that case, but when I attach it to the TLS server, the client throws the following error when attempting to connect:
```
Quobject.EngineIoClientDotNet.Client.EngineIOException: xhr poll error ---> System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.<Create>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.Create()
   --- End of inner exception stack trace ---
```

**Comment by mattqs** [comment]
I used [https](https://nodejs.org/api/https.html) in test [server.js](https://github.com/Quobject/SocketIoClientDotNet/blob/master/TestServer/server.js).

**Comment by TadeoArmenta** [comment]
Your tls certs are valid for the domain in which you are testing?

certs only works on the domain/ip they were signed for, so if you try to use them in your development machine, they behave like this.

if the certs are valid, are you using nginx?

if so, you have to set some headers to avoid this kind of troubles

something like this:


server {
    listen 80;
    server_name MyDomain.org;
    location / {
        return 301 https://$host$request_uri;
    }
     
}

server {

    listen 443;
    server_name MyDomain.org;

    ssl_certificate           /var/www/MyDomainweb/ssl/MyDomain_org-ssl-bundle.crt;
    ssl_certificate_key       /var/www/MyDomainweb/ssl/MyDomain.org.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/MyDomain_org.access.log;

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_http_version       1.1;
      proxy_set_header         Upgrade $http_upgrade;
      proxy_set_header         Connection "upgrade";

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          https://localhost:3000;
      proxy_read_timeout  90;
    }
   
  }

obviously, you can avoid the nginx problem,  connecting your c# directly to node

socket = IO.Socket("https://mydomain.org:3000", opt);

**Comment by thuron** [comment]
I'll try that for sure, but I'm confused about something: I'm not creating a website or anything http related for this server. I'm building a server that will communicated with a windows .net client. Is it in such case still desired to communicate over https or should I rather use a TLS socket instead, and if so, would I still be able to use Socket.IO and the Socket.IO .net client?

**Comment by mattqs** [comment]
Socket.IO is using http(s) or web sockets depending on the connection available. If it cannot use websockets it will always automatically fall back to http(s). 

I am not familiar with TLS socket and therefore you might find a better answer about this at stackoverflow.com.
