### ISSUE TITLE
Connection is never upgraded to WebSocket

### ISSUE THREAD

**Issue by OrMan123** [Quobject/SocketIoClientDotNet#70]
I have a simple code that I am testing against a socket.io server (chat.socket.io)

            IO.Options testOptions = new IO.Options();
            string url = "http://chat.socket.io";
            testOptions.ForceNew = true;
            testOptions.AutoConnect = true;
            testOptions.Upgrade = true;

            Socket _socket = IO.Socket(url, testOptions);

            _socket.On("data", (data) =>
            {
                Console.WriteLine(data.ToString());
            });

When I look at the connection through fiddler I see the transport is only polling
I have no Idea why

Also about every 2 minutes the client disconnects and reconnects

I am using the latest version

**Comment by mattqs** [comment]
Please use stackoverflow.com for these kind of problems.

**Comment by leohsu91** [comment]
same problem
