### ISSUE TITLE
Support more than 1 event parameter 

### ISSUE THREAD

**Issue by LiranBo** [Quobject/SocketIoClientDotNet#71]
Hi,

I use your library in my MVC ASP .NET project, I have an external API which I need to connect to, the problem I have is that some of the API event functions use more than 1 parameter, for example:

            socket.On("eventName",  (log, data) =>
            {
                results = data.ToString();
            });

This is the error I get:
>Error	2	Delegate 'System.Action' does not take 2 arguments	

Is there any way to work around that issue?

**Just to be clear, I have no control over the external API, so I can't change their functions.

Thank,

Liran

**Comment by mattqs** [comment]
See https://github.com/Quobject/SocketIoClientDotNet/issues/51
