### ISSUE TITLE
Room and on Event in room

### ISSUE THREAD

**Issue by CicciMTS** [Quobject/SocketIoClientDotNet#73]
Hello, I'm trying to connect a NodeJS with Socket.io (Javascript) and SocketIoClientDotNet. I need to join SocketIoClientDotNet client in a room, but when i emit an event from socket.io javascript into the room, SocketIoClientDotNet client can't listen the event. I don't retrieve any kind of error. 

This is the pastebin with the code: http://pastebin.com/X52X6KBu
Thx

**Comment by TadeoArmenta** [comment]
Try something like this.


//-------------- App.js (Socket.io) ----------------- //
   var room = io.of('/myroom');


room.on('connection', function(socket){
    console.log('Client connected!');
 
    socket.on('joinRoom', function(room){
        socket.join(room);
    });
 
    socket.on('nameEv', function(data){
        console.log('From .Net: ', data);
        io.in('nameRoom').emit('successEv', 'Ok');
    });
});
 //-------------- C# SocketIoClientDotNet ----------------- //
using Quobject.SocketIoClientDotNet.Client;
 
IO.Options optConnect = new IO.Options();
optConnect.Timeout = 3000;
 
//var socket = IO.Socket("http://hostname:3000", optConnect);
 
Manager manager = new Manager(new Uri("http://hostname:3000"), optConnect;

var socket = manager.Socket("/myroom");


socket.On(Socket.EVENT_CONNECT, (data) =>
{                    
        socket.Emit("join", "nameRoom");
        socket.Emit("nameEv", "Hello world!");
});
 
socket.On("successEv", (data) =>
{  
        MessageBox.Show(data.ToString());

**Comment by mattqs** [comment]
stackoverflow.com is a far better place to ask this question.
