### ISSUE TITLE
Wait for Callback

### ISSUE THREAD

**Issue by zeeshanjan82** [Quobject/SocketIoClientDotNet#74]
I am using this library for communicating with my NodeJS Service which is running on an static ip address and has socket.io integrated. After I add reference to this library in my C# project , I am using the following lines of code to Emit an event with a data object
```C#
            socket.Emit(eventName, new AckImpl((result, n) =>
            {
                callback(result);
            }), new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(data));
````
However I would like to wait for the callback before the execution moves ahead. Currently I am able to call socket.Emit but then the execution context moves to further lines of code, however I would like to wait for the callback. 

Is there any way to wait for the callback?

**Comment by mattqs** [comment]
stackoverflow.com is a far better place to ask this question.

**Comment by thEpisode** [comment]
WTF is this? if you create this product....
