### ISSUE TITLE
Exception of type 'System.TimeZoneNotFoundException' was thrown.

### ISSUE THREAD

**Issue by Fujikatoma** [Quobject/SocketIoClientDotNet#80]
System.TimeZoneNotFoundExceptionException of type 'System.TimeZoneNotFoundException' was thrown.
System.TimeZoneInfo.GetMonoTouchData(string name, bool throw_on_error)TimeZoneInfo.MonoTouch.cs:103
System.TimeZoneInfo.CreateLocal()TimeZoneInfo.MonoTouch.cs:49
System.TimeZoneInfo.get_Local()TimeZoneInfo.cs:75
System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc(DateTime time, ref bool isAmbiguousLocalDst)TimeZoneInfo.cs:427
System.DateTime.get_Now()datetime.cs:950
Quobject.EngineIoClientDotNet.Client.Transports.Polling.Uri()
Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.Request(RequestOptions opts)
Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.DoPoll()
Quobject.EngineIoClientDotNet.Client.Transports.Polling.Poll()
Quobject.EngineIoClientDotNet.Client.Transports.Polling.DoOpen()
Quobject.EngineIoClientDotNet.Client.Transport.Open()
Quobject.EngineIoClientDotNet.Client.Socket.<Open>c__AnonStorey0.<>m__0()
System.Threading.Tasks.Task.InnerInvoke()Task.cs:2901
System.Threading.Tasks.Task.Execute()Task.cs:2523

i got this error when using you plugin with Xamarin iOS on ios 9.2

**Comment by mattqs** [comment]
@Fujikatoma This is an issue with Xamarin.iOS, I recommend you follow three steps:

1. Post a question at stackoverflow.com with detailed enough information to reproduce this exception.
2. Email xamarin support and provide link to your stackoverflow.com question. 
3. Update this issue with a link to  your stackoverflow.com question.

Step 2 requires a business xamarin licence, in case you don't have this, I can help you with this by using my free open source licence.

**Comment by Fujikatoma** [comment]
@mattqs
Thanks for the answer, reproducing is difficult because i don't know how. It only happen on one of my 10 Test Devices. I'll try to give as much details as i can. It also happens when i use Xamarin.Insights. 
It would be great if you contact the support , because i only have an Indie account
