### ISSUE TITLE
Establishing connection with flask server

### ISSUE THREAD

**Issue by shimrithoori** [Quobject/SocketIoClientDotNet#83]
Hi, I wrote a server in flask and I want to create web socket between it and my c# client.  
The problem is that the client keeps sending new connection requests to the server and the web socket transport is never established. 

This is my flask server code: 

    from flask import Flask
    from flask.ext.socketio import SocketIO, emit

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret!'
    socketio = SocketIO(app)

    @app.route('/')
    def home():
        return "hello"

    @socketio.on('connect')
    def connect():
        print("CONNECTED")

    @socketio.on("message")
    def test():
        print("TEST WORKS")

    if __name__ == '__main__':
        socketio.run(app)

c# client :

    public static class EnvConnections {

    public static IO.Options CreateOptions() {
        var options = new IO.Options();
        options.Port = 5000;
        options.Hostname = "127.0.0.1";
        options.ForceNew = true;

        return options;
    }

    public static void Connect() {
        Uri uri = new Uri("http://127.0.0.1:5000");
        var socket = IO.Socket(uri, CreateOptions()); //also tried to create the socket only with url IO.Socket("http://127.0.0.1:5000")

        socket.On(Socket.EVENT_CONNECT, () => {
            Console.Write("EVENT_CONNECT");
            socket.Disconnect();
        });

    socket.Connect(); //tried to remove this 
    Console.ReadLine();
} 

Server log : 

    fb0f4c189334468dba90255880b528a4: Sending packet MESSAGE with 0
    127.0.0.1 - - [20/Jan/2016 17:49:13] "GET /socket.io/?EIO=3&transport=polling&t=635889089536079075-2035&b64=1 HTTP/1.1" 200 355 0.002000
    5cea6ce4dd8b47d79e79dd96747c26e4: Sending packet OPEN with {'pingTimeout': 60000, 'sid': '5cea6ce4dd8b47d79e79dd96747c26e4', 'upgrades': ['websocket'], 'pingInterval': 25000}
     5cea6ce4dd8b47d79e79dd96747c26e4: Sending packet MESSAGE with 0
    127.0.0.1 - - [20/Jan/2016 17:49:13] "GET /socket.io/?EIO=3&transport=polling&t=635889089536109077-2036&b64=1 HTTP/1.1" 200 355 0.003000
    f768281808204af995421b4dbb2cda1c: Sending packet OPEN with {'pingTimeout': 60000, 'sid': 'f768281808204af995421b4dbb2cda1c', 'upgrades': ['websocket'], 'pingInterval': 25000}
    CONNECTED
    CONNECTED
    f768281808204af995421b4dbb2cda1c: Sending packet MESSAGE with 0
    127.0.0.1 - - [20/Jan/2016 17:49:13] "GET /socket.io/?EIO=3&transport=polling&t=635889089536149079-2037&b64=1 HTTP/1.1" 200 355 0.002000
    e4eb16fcd12f41898ba58a309014b85c: Sending packet OPEN with {'pingTimeout': 60000, 'sid': 'e4eb16fcd12f41898ba58a309014b85c', 'upgrades': ['websocket'], 'pingInterval': 25000}
    e4eb16fcd12f41898ba58a309014b85c: Sending packet MESSAGE with 0
    127.0.0.1 - - [20/Jan/2016 17:49:13] "GET /socket.io/?EIO=3&transport=polling&t=635889089536179081-2038&b64=1 HTTP/1.1" 200 355 0.002000
    70f45826d89b42bba3842e41b8ae8b08: Sending packet OPEN with {'pingTimeout': 60000, 'sid': '70f45826d89b42bba3842e41b8ae8b08', 'upgrades': ['websocket'], 'pingInterval': 25000}
    70f45826d89b42bba3842e41b8ae8b08: Sending packet MESSAGE with 0
    127.0.0.1 - - [20/Jan/2016 17:49:13] "GET /socket.io/?EIO=3&transport=polling&t=635889089536219083-2039&b64=1 HTTP/1.1" 200 355 0.002000
    CONNECTED
    CONNECTED

**Comment by mattqs** [comment]
http://stackoverflow.com/questions/ask
