### ISSUE TITLE
Rooms support

### ISSUE THREAD

**Issue by NeoLegends** [Quobject/SocketIoClientDotNet#85]
It would be great if this library supported socket.io's concept of rooms. A room is a subdivision of a namespace. One can be part of multiple rooms at the same time. The missing room support is also referenced in #73 and #78.

**Comment by mattqs** [comment]
This is the Socket.IO Client Library for C#, which is ported from the JavaScript client version 1.1.0. Anything that is not in the Javascript client won't work here either.

**Comment by NeoLegends** [comment]
So this library will not be getting new features?

**Comment by mattqs** [comment]
As there are all features of the JavaScript client version 1.1.0 already implemented, there are no more new features planned.

**Comment by kumaralg2** [comment]
Does this library supports rooms?
