### ISSUE TITLE
SocketIO 1.4.5 server compatible?

### ISSUE THREAD

**Issue by ChickenMythic** [Quobject/SocketIoClientDotNet#87]
First thanks for this lib!
Second, it's more a question rather than an issue.

**Is this lib compatible with server using SocketIO 1.4.5**?
The server I'm trying to connect to uses v1.4.5 and I can connect over **http** (most of the time) but I can't receive events 90% of the time. I receive this EVENT_ERROR :

```
Quobject.EngineIoClientDotNet.Client.EngineIOException: xhr post error ---> System.Net.WebException: The remote server returned an error: BadRequest.
   at MS.Internal.Modern.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   at MS.Internal.Modern.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.GetResponseCallback(IAsyncResult asynchronousResult)
   --- End of inner exception stack trace ---
```

If it's not 1.4.5 compatible then it explains those exception + the fact that I don't receive events most of the time. Also it might be the reason why I simply can't connect over **https**.
If so, rather than upgrading the lib to 1.4.5 compatible, would there be another wait?

Thanks in advance.

EDIT:
I tried to set **IO.Option.ForceJsonp** to _true_ and the error just changed to 
```
Quobject.EngineIoClientDotNet.Client.EngineIOException: xhr post error ---> System.Net.WebException: The remote server returned an error: BadRequest.
   at MS.Internal.Modern.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   at MS.Internal.Modern.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.GetResponseCallback(IAsyncResult asynchronousResult)
   --- End of inner exception stack trace ---
```

**Comment by ChickenMythic** [comment]
Specifying transports in option makes it work:

```
options.Transports = Quobject.Collections.Immutable.ImmutableList<string>.Empty;
options.Transports = options.Transports.Add("websocket");
options.Transports = options.Transports.Add("flashsocket");
options.Transports = options.Transports.Add("htmlfile");
options.Transports = options.Transports.Add("xhr-polling");
options.Transports = options.Transports.Add("jsonp-polling");
```
Most of them might be useless regarding the server config but at least it works. (The server only uses "websocket" and "jsonp-polling".)
Also, our ping/pong test events respond faster with those new options.

**Comment by nova76** [comment]
I'm a beginner in c#. How to work this my code?
i tried this:
var options =  CreateOptions()
but:
Error	1	The name 'CreateOptions' does not exist in the current context

**Comment by mattqs** [comment]
http://stackoverflow.com/questions/ask
