### ISSUE TITLE
TLS Client-Authentication

### ISSUE THREAD

**Issue by alvapin** [Quobject/SocketIoClientDotNet#88]
Hello.

I am working in application that requires some extra security. I have successfully implemented tls/ssl with server certificates. Works with a normal browser and with this library.

Now I would like to implement Client-Authentication. So far I couldn't find any information about this. Does this library support client authentication? If so could you be kind and provide an example.

Regards

Alvaro

**Comment by mattqs** [comment]
This Client Library for C#, was ported from the JavaScript client version 1.1.0.

It has everything that was in the JavaScript client version 1.1.0.

I'm not an expert in TLS authentication.
