### ISSUE TITLE
Client disconnects after a minute and a half

### ISSUE THREAD

**Issue by mlantin** [Quobject/SocketIoClientDotNet#97]
I've just started using this library with Unity. My server is sending updates about 30 times a second. After about 1.5 minutes of receiving the events perfectly the client just disconnects. It does not attempt to reconnect.

I will also need to send updates about 30 times/second. I'm not sure if that is possible given another open issue that I saw which says the events are buffered before emit?

My most urgent issue is the disconnecting. Is there a way to find out why it's suddenly disconnecting?

**Comment by mattqs** [comment]
http://stackoverflow.com/questions/ask
